interface EmailParams {
  to: string
  recipientName: string
  storeName: string
  storeLocation: string
  reportDate: string
  reportRole: string
  reportContent: string
}

export async function sendReportEmail({
  to,
  recipientName,
  storeName,
  storeLocation,
  reportDate,
  reportRole,
  reportContent,
}: EmailParams) {
  // In a real implementation, you would use a service like Resend, SendGrid, or similar
  // For now, we'll simulate the email sending process

  const emailTemplate = generateEmailTemplate({
    recipientName,
    storeName,
    storeLocation,
    reportDate,
    reportRole,
    reportContent,
  })

  try {
    // Simulate email sending - replace with actual email service
    console.log(`[EMAIL] Sending report to ${to}`)
    console.log(`[EMAIL] Subject: Daily ${reportRole} Report - ${storeName} (${reportDate})`)
    console.log(`[EMAIL] Content: ${emailTemplate.substring(0, 200)}...`)

    // In production, replace this with actual email service call:
    // const response = await fetch('https://api.resend.com/emails', {
    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({
    //     from: 'reports@dqreporting.com',
    //     to: [to],
    //     subject: `Daily ${reportRole} Report - ${storeName} (${reportDate})`,
    //     html: emailTemplate,
    //   }),
    // })

    return { success: true, message: "Email sent successfully" }
  } catch (error) {
    console.error("Error sending email:", error)
    return { success: false, error: "Failed to send email" }
  }
}

function generateEmailTemplate({
  recipientName,
  storeName,
  storeLocation,
  reportDate,
  reportRole,
  reportContent,
}: Omit<EmailParams, "to">) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Report - ${storeName}</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #1e40af; color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }
    .content { background: #f8fafc; padding: 30px; border-radius: 0 0 8px 8px; }
    .report-content { background: white; padding: 20px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #1e40af; }
    .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 14px; }
    .store-info { background: #e0f2fe; padding: 15px; border-radius: 6px; margin: 15px 0; }
    h1 { margin: 0; font-size: 24px; }
    h2 { color: #1e40af; margin-top: 0; }
    .date { font-size: 16px; opacity: 0.9; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🍦 DQ Daily Report</h1>
    <div class="date">${new Date(reportDate).toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    })}</div>
  </div>
  
  <div class="content">
    <p>Hello ${recipientName},</p>
    
    <p>Here's your daily ${reportRole} report for <strong>${storeName}</strong>.</p>
    
    <div class="store-info">
      <strong>📍 ${storeName}</strong><br>
      ${storeLocation}
    </div>
    
    <div class="report-content">
      <h2>📊 ${reportRole.charAt(0).toUpperCase() + reportRole.slice(1)} Report</h2>
      <div style="white-space: pre-wrap; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
        ${reportContent}
      </div>
    </div>
    
    <p>This report was automatically generated by the DQ AI Reporting System.</p>
    
    <p>Best regards,<br>
    <strong>DQ Reporting Team</strong></p>
  </div>
  
  <div class="footer">
    <p>This is an automated message from DQ AI Reporting Tool.<br>
    If you have questions, please contact your store manager.</p>
  </div>
</body>
</html>
  `
}

export async function sendSMSReport(phoneNumber: string, message: string) {
  // In a real implementation, you would use a service like Twilio
  console.log(`[SMS] Sending to ${phoneNumber}: ${message.substring(0, 100)}...`)

  try {
    // Simulate SMS sending - replace with actual SMS service
    // const response = await fetch('https://api.twilio.com/2010-04-01/Accounts/YOUR_ACCOUNT_SID/Messages.json', {
    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Basic ${Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64')}`,
    //     'Content-Type': 'application/x-www-form-urlencoded',
    //   },
    //   body: new URLSearchParams({
    //     From: process.env.TWILIO_PHONE_NUMBER,
    //     To: phoneNumber,
    //     Body: message,
    //   }),
    // })

    return { success: true, message: "SMS sent successfully" }
  } catch (error) {
    console.error("Error sending SMS:", error)
    return { success: false, error: "Failed to send SMS" }
  }
}
